import type { NextPage } from 'next'
import Head from 'next/head'
import { useTasksQuery, TasksQuery, TasksDocument } from '../generated/graphql-frontend';
import { initializeApollo } from '../lib/client';
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {

  //Esta funcion se creo con graphql-codegen con el plugin de typescript-react-apollo
  const result = useTasksQuery();
  const tasks = result.data?.tasks;

  return (
    <div className={styles.container}>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        tasks && tasks.length > 0 && tasks.map((task) => (
          <div key={task.id}>
            {task.title} {task.status}
          </div>
        ))
      }
    </div>
  )
}

export const getStaticProps = async () => {
  const apolloClient = initializeApollo();
  await apolloClient.query<TasksQuery>({
    query: TasksDocument
  })

  return {
    props: {
      initialApolloState: apolloClient.cache.extract()
    }
  }
}

export default Home
